version: "3.4"
services:
  jupyterlab:
    user: 1000:1000
    container_name: jupyterlab
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./jupyterLabData/workspace:/home/jovyan/workspace:rw
    environment:
        JUPYTER_TOKEN: "ADJES38s3"


networks: 
  default: 
    external: 
      name: common-network 
