version: "3.4"
services:
  gatsby-server:
    platform: linux/amd64
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
    ports:
      - "8008:8888"
    volumes:
      - ./jupyterLabData:/home/jovyan/work:rw
    environment:


