version: "3.4"
services:
  jupyterlab:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./jupyterLabData:/home/jovyan/work:rw
    environment:
        JUPYTER_TOKEN: "ADJES38s3"


